name: ems
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  google_fonts: ^6.1.0
  js: ^0.7.2   
  intl: ^0.18.1 
  fluttertoast: ^8.0.9
  dynamic_background: ^0.5.0
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/login_bg.jpg
